name: build
on:
  workflow_dispatch:

jobs:
  windows:
    name: windows
    runs-on: windows-2022

    steps:

    - uses: microsoft/setup-msbuild@v3

    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build
      run: |
        mkdir bin

        msbuild code\win32\msvc2017\quake3e-ded.vcxproj -p:TargetName=quake3e.ded,Configuration=Release,Platform=x64 /p:PlatformToolset=v143
        copy code\win32\msvc2017\output\quake3e.ded.exe bin\quake3e.ded.exe
        msbuild code\win32\msvc2017\quake3e-ded.vcxproj -p:TargetName=quake3e.ded,Configuration=Release,Platform=x64 -t:Clean

        msbuild code\win32\msvc2017\renderer.vcxproj -p:Configuration=Release,Platform=x64 /p:PlatformToolset=v143
        msbuild code\win32\msvc2017\quake3e.vcxproj -p:TargetName=quake3e,Configuration=Release,Platform=x64,UseWasapi=USE_WASAPI=0 /p:PlatformToolset=v143
        copy code\win32\msvc2017\output\quake3e.exe bin\quake3e.exe
        msbuild code\win32\msvc2017\renderer.vcxproj -p:Configuration=Release,Platform=x64 -t:Clean
        msbuild code\win32\msvc2017\quake3e.vcxproj -p:TargetName=quake3e,Configuration=Release,Platform=x64,UseWasapi=USE_WASAPI=0 -t:Clean

        msbuild code\win32\msvc2017\renderervk.vcxproj -p:Configuration=Release,Platform=x64 /p:PlatformToolset=v143
        msbuild code\win32\msvc2017\quake3e.vcxproj -p:TargetName=quake3e,Configuration=Release,Platform=x64,UseWasapi=USE_WASAPI=0 /p:PlatformToolset=v143
        copy code\win32\msvc2017\output\quake3e.exe bin\quake3e-vulkan.exe
        msbuild code\win32\msvc2017\renderervk.vcxproj -p:Configuration=Release,Platform=x64 -t:Clean
        msbuild code\win32\msvc2017\quake3e.vcxproj -p:TargetName=quake3e,Configuration=Release,Platform=x64,UseWasapi=USE_WASAPI=0 -t:Clean

    - uses: actions/upload-artifact@v7
      with:
        name: windows
        path: bin
        if-no-files-found: error
        retention-days: 5

  linux:
    name: linux
    runs-on: ubuntu-24.04

    steps:

    - name: Install tools
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev libsdl2-dev

    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(nproc) ARCH=x86_64 COMPILE_ARCH=x86_64 CC=gcc DESTDIR=bin USE_SDL=1 USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=vulkan CNAME=quake3e-vulkan BUILD_SERVER=0
        make clean ARCH=x86_64
        make install -j$(nproc) ARCH=x86_64 COMPILE_ARCH=x86_64 CC=gcc DESTDIR=bin USE_SDL=1 USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=opengl

    - uses: actions/upload-artifact@v7
      with:
        name: linux
        path: bin
        if-no-files-found: error
        retention-days: 5

  macos:
    name: macos
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    steps:

    - name: Trust taps
      run: brew trust aws/tap azure/bicep

    - name: Install tools
      run: brew install coreutils sdl2 # pkg-config

    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(sysctl -n hw.logicalcpu) ARCH=${{ matrix.arch }} CC=clang DESTDIR=bin INSTALL=ginstall USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=vulkan CNAME=quake3e-vulkan BUILD_SERVER=0 STRIP=echo
        make clean ARCH=${{ matrix.arch }}
        make install -j$(sysctl -n hw.logicalcpu) ARCH=${{ matrix.arch }} CC=clang DESTDIR=bin INSTALL=ginstall USE_RENDERER_DLOPEN=0 RENDERER_DEFAULT=opengl STRIP=echo

    - uses: actions/upload-artifact@v7
      with:
        name: macos-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  create-release:
    needs: [windows, linux, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8

      - name: Create binary archives
        run: |
          7z a -r quake3e-UrT-linux.zip           ./linux/*
          7z a -r quake3e-UrT-windows.zip         ./windows/*
          7z a -r quake3e-UrT-macos-x86_64.zip    ./macos-x86_64/*
          7z a -r quake3e-UrT-macos-aarch64.zip   ./macos-aarch64/*

      - name: Set Date Tag
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Upload Releases
        uses: svenstaro/upload-release-action@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            *.zip
          tag: ${{ steps.date.outputs.DATE }}
          release_name: ${{ steps.tag.outputs.DATE }}
          overwrite: true
          file_glob: true
          draft: false
          make_latest: true